config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists do
    resources :todo_tasks do
    member do
      patch :complete
      patch :priority
     end
  end
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "todo_lists#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/priority.rb
class Priority < ApplicationRecord
    def priority_label
        label
       end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
    has_many :todo_tasks
end

app/models/todo_task.rb
class TodoTask < ApplicationRecord
  belongs_to :todo_list
  enum priority: [:high, :medium, :low]
  def completed?
    !completed_at.blank?
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_list_params
      params.require(:todo_list).permit(:title)
    end
end

app/controllers/todo_tasks_controller.rb
class TodoTasksController < ApplicationController
    before_action :set_todo_list
    before_action :set_todo_task, except: [:create]
    def create
        @todo_task = @todo_list.todo_tasks.create(todo_task_params)
        redirect_to @todo_list
    end
    
    def set_todo_list
        @todo_list = TodoList.find(params[:todo_list_id])
    end
    
    def todo_task_params
        params[:todo_task].permit(:task, :deadline, :priority)
    end

    def complete
        @todo_task.update_attribute(:completed_at, Time.now)
        redirect_to @todo_list, notice: "Todo task completed"
    end

    def set_todo_task
        @todo_task = @todo_list.todo_tasks.find(params[:id])
    end

    def destroy
        @todo_task = @todo_list.todo_tasks.find(params[:id])
        if @todo_task.destroy
             flash[:success] = "Todo List item was deleted."
        else
             flash[:error] = "Todo List item could not be deleted."
        end
        redirect_to @todo_list 
       end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/todo_tasks_helper.rb
module TodoTasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1 class="todo_list_title">Editing Todo List</h1>
<div class="forms">
<%= render 'form', todo_list: @todo_list %>
</div>
<div class="links">
<%= link_to 'Cancel', todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
<% @todo_lists.each do |todo_list| %>
<div class="index_row clearfix">
  <p class="todo_list_title"><%= link_to todo_list.title, todo_list %></p>
</div>
<% end %>
<div class="index_row clearfix ">
  <%= link_to "New Todo List", new_todo_list_path %>
</div>

<!--
<p id="notice"><%= notice %></p>

<h1>Todo Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.title %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo List', new_todo_list_path %>
-->

app/views/todo_lists/new.html.erb
<h1 class="todo_list_title">New Todo List</h1>
<div class="forms">
<%= render 'form', todo_list: @todo_list %>
</div>
<div class="links">
<%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="todo_list_title"><%= @todo_list.title %></h2><br>

<div id="todo_tasks_wrapper">
 <%= render @todo_list.todo_tasks %>
 <div id="form">
  <%= render "todo_tasks/form" %>
 </div>
</div>

<div class="links">
 <%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
 <!--<%= link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" } %> |-->
 <%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_tasks/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_tasks.build]) do |f| %>
<div class="field"> 
    <%= f.label :task %>
    <%= f.label :deadline %> 
    <%= f.label :priority %>
    
    <%= f.text_field :task %>
   
    <%= f.date_select :deadline, min: Date.today  %> 
    <%= f.select :priority, TodoTask.priorities.keys %>
    
  </div>
 <%= f.submit %>
<% end %>

app/views/todo_tasks/_todo_task.html.erb
<div class="row clearfix">
  <% if todo_task.completed? %>

    <div class="todo_task done">
      <p><%= todo_task.task %></p>
    </div>
    <div class="todo_priority done">
    <p><%= todo_task.priority %></p>
    </div>
    <div class="todo_deadline done">
      <p><%= todo_task.deadline %> </p>
    </div>

    <div class="complete">
      <%= link_to complete_todo_list_todo_task_path(@todo_list, todo_task.id), method: :patch do %>
    <i style="opacity: 1;" class="fa fa-check"></i>
   <% end %>
    </div>
    <div class="trash">
      <%= link_to todo_list_todo_task_path(@todo_list, todo_task.id), method: :delete, data: { confirm: "Are you sure?" } do %>
    <i class="fa fa-trash"></i>
   <% end %>
    </div>
  <% else %>
    
    <div class="todo_task">
      <p><%= todo_task.task %></p>
    </div>
    <div class="todo_priority">
    <p><%= todo_task.priority %></p>
    </div>
    <div class="todo_deadline">
      <p><%= todo_task.deadline %> </p>
    </div>
    <div class="complete"><%= link_to complete_todo_list_todo_task_path(@todo_list, todo_task.id), method: :patch do %>
    <i class="fa fa-circle-thin"></i>
   <% end %>
   </div>
    <div class="trash">
      <%= link_to todo_list_todo_task_path(@todo_list, todo_task.id), method: :delete, data: { confirm: "Are you sure?" } do %>
    <i class="fa fa-trash"></i>
   <% end %>
    </div>
  <% end %>
</div>